name: Jar

on: [ push, pull_request, workflow_dispatch ]

env:
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Execute Gradle `jar` task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jar
          cache-read-only: |
            ${{ github.ref != 'refs/heads/main' && 
                github.ref != 'refs/heads/dev' }}
          gradle-home-cache-includes: |
            caches
            notifications
            jdks

      - name: Upload `jar`
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/kotgll-*.jar