name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --scan

      - name: Upload 'test' report artifact
        uses: actions/upload-artifact@v3
        with:
          name: TestReport
          path: build/reports/tests/test/index.html

      - name: Render 'test' report
        uses: dorny/test-reporter@v1
        with:
          path: 'build/reports/tests/test/*'
          reporter: 'java-junit'
          list-tests: 'all'
          max-annotations: '50'