name: Publish

on:
  release:
    types: [ created ]

env:
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Publish package
        uses: gradle/gradle-build-action@v3
        with:
          arguments: publish
          cache-read-only: |
            ${{ github.ref != 'refs/heads/main' && 
                github.ref != 'refs/heads/dev' }}
          gradle-home-cache-includes: |
            caches
            notifications
            jdks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/kotgll-*.jar
