name: Test

on: [ push, pull_request, workflow_dispatch ]

env:
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Execute Gradle `test` task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --scan
          cache-read-only: |
            ${{ github.ref != 'refs/heads/main' && 
                github.ref != 'refs/heads/dev' }}
          gradle-home-cache-includes: |
            caches
            notifications
            jdks

      - name: Upload `test` report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: TestReport-${{ matrix.os }}
          path: build/reports/tests/